name: ddb_wfs tests
on:
  push:
    paths:
    - 'media-plugins/deadbeef-waveform-seekbar/**'
  pull_request:
    paths:
    - 'media-plugins/deadbeef-waveform-seekbar/**'

jobs:
  ebuild:
    if: github.repository == 'PF4Public/gentoo-overlay'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        use:
          - ''

    steps:
      - uses: actions/checkout@v2

      - uses: lots0logs/gh-action-get-changed-files@2.1.4
        id: files
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install ddb_wfs with "${{ matrix.use }}"
        uses: pf4public/gentoo-docker-action@master
        with:
            added: ${{ steps.files.outputs.added }}
            modified: ${{ steps.files.outputs.modified }}
            tool: ebuild
            action: install
            params: ${{ matrix.use }}