name: font-manager tests
on:
  push:
    paths:
    - 'app-misc/font-manager/**'
  pull_request:
    paths:
    - 'app-misc/font-manager/**'

jobs:
  ebuild:
    if: github.repository == 'PF4Public/gentoo-overlay'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        use:
          - 'manager viewer'
          - 'reproducible'
          - 'thunar nautilus'
          - 'doc'
          # not testing nemo

    steps:
      - uses: actions/checkout@v2

      - uses: lots0logs/gh-action-get-changed-files@2.1.4
        id: files
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Trying to install font-manager with "${{ matrix.use }}"
        uses: pf4public/gentoo-docker-action@master
        with:
            added: ${{ steps.files.outputs.added }}
            modified: ${{ steps.files.outputs.modified }}
            action: install
            use: ${{ matrix.use }}