name: sb-hosts tests
on:
  push:
    paths:
    - 'net-misc/sb-hosts/**'
  pull_request:
    paths:
    - 'net-misc/sb-hosts/**'

jobs:
  ebuild:
    if: github.repository == 'PF4Public/gentoo-overlay'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        use:
          - fakenews gambling porn social
          - ''
          - fakenews social
          - fakenews gambling social
          - gambling

    steps:
      - uses: actions/checkout@v2

      - uses: lots0logs/gh-action-get-changed-files@2.1.4
        id: files
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Trying to install sb-hosts with "${{ matrix.use }}"
        uses: pf4public/gentoo-docker-action@master
        with:
            added: ${{ steps.files.outputs.added }}
            modified: ${{ steps.files.outputs.modified }}
            action: install
            use: ${{ matrix.use }}
