name: ungoogled-chromium tests
on:
  push:
    paths:
    - 'www-client/ungoogled-chromium/**'
  pull_request:
    paths:
    - 'www-client/ungoogled-chromium/**'

jobs:
  ebuild:
    if: github.repository == 'PF4Public/gentoo-overlay'
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental || false }}
    strategy:
      fail-fast: false
      matrix:
        use:
          - vaapi -system-libvpx
          - vaapi ozone -system-libvpx
          - vdpau
          - cfi thinlto
          - -clang
          - enable-driver hangouts
          - headless ozone
          - pulseaudio
          - suid
          - ozone
          - ozone ozone-wayland
          - widevine
          - custom-cflags
        include:
          - use: vaapi system-libvpx
            experimental: true
          - use: system-libvpx
            experimental: true

    steps:
      - uses: actions/checkout@v2

      - uses: lots0logs/gh-action-get-changed-files@2.1.4
        id: files
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Trying to configure ungoogled-chromium with "${{ matrix.use }}"
        uses: pf4public/gentoo-docker-action@master
        with:
            added: ${{ steps.files.outputs.added }}
            modified: ${{ steps.files.outputs.modified }}
            action: configure
            use: ${{ matrix.use }}