name: vscode tests
on:
  push:
    paths:
    - 'app-editors/vscode/**'
  pull_request:
    paths:
    - 'app-editors/vscode/**'

jobs:
  ebuild:
    if: github.repository == 'PF4Public/gentoo-overlay'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        use:
          - 'build-online'
          - '-build-online'
          - 'badge-providers builtin-extensions'
          - 'ignore-gpu-blacklist'
          - 'insiders'
          - 'liveshare'
          - 'openvsx'
          - 'substitute-urls'

    steps:
      - uses: actions/checkout@v2

      - uses: lots0logs/gh-action-get-changed-files@2.1.4
        id: files
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Trying to install vscode with "${{ matrix.use }}"
        uses: pf4public/gentoo-docker-action@master
        with:
            added: ${{ steps.files.outputs.added }}
            modified: ${{ steps.files.outputs.modified }}
            action: install
            use: ${{ matrix.use }}